# Generated by Django 4.2.6 on 2023-10-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('firstName', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.IntegerField()),
                ('confpassword', models.IntegerField()),
            ],
        ),
    ]
