# Generated by Django 4.2.6 on 2023-10-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regandlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='confpassword',
            field=models.IntegerField(max_length=22),
        ),
        migrations.AlterField(
            model_name='reg',
            name='password',
            field=models.IntegerField(max_length=22),
        ),
    ]
