# Generated by Django 4.2.6 on 2023-10-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regandlogin', '0002_alter_reg_confpassword_alter_reg_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='confpassword',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reg',
            name='password',
            field=models.IntegerField(),
        ),
    ]
